logistics/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "tracking"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracking.urls')),
    # path('orders/', include('tracking.urls')),  # Include your app's URLs here
]

tracking/urls.py
from django.urls import path
from . import views
app_name = "tracking"

urlpatterns = [
    # User URLs
    path('api/users/', views.getUsers),
    path('api/users/create/', views.addUser),
    path('api/users/read/<str:pk>/', views.getUser),
    path('api/users/update/<str:pk>/', views.updateUser),
    path('api/users/delete/<str:pk>/', views.deleteUser),

    # Customer URLs
    path('api/customers/', views.getCustomers),
    path('api/customers/create/', views.addCustomer),
    path('api/customers/read/<str:pk>/', views.getCustomer),
    path('api/customers/update/<str:pk>/', views.updateCustomer),
    path('api/customers/delete/<str:pk>/', views.deleteCustomer),

    # Order URLs
    path('api/orders/', views.getOrders),
    path('api/orders/create/', views.addOrder),
    path('api/orders/read/<str:pk>/', views.getOrder),
    path('api/orders/update/<str:pk>/', views.updateOrder),
    path('api/orders/delete/<str:pk>/', views.deleteOrder),

    # OrderItem URLs
    path('api/order-items/', views.getOrderItems),
    path('api/order-items/create/', views.addOrderItem),
    path('api/order-items/read/<str:pk>/', views.getOrderItem),
    path('api/order-items/update/<str:pk>/', views.updateOrderItem),
    path('api/order-items/delete/<str:pk>/', views.deleteOrderItem),

    # Transaction URLs
    path('api/transactions/', views.getTransactions),
    path('api/transactions/create/', views.addTransaction),
    path('api/transactions/read/<str:pk>/', views.getTransaction),
    path('api/transactions/update/<str:pk>/', views.updateTransaction),
    path('api/transactions/delete/<str:pk>/', views.deleteTransaction),

    # Warehouse URLs
    path('api/warehouses/', views.getWarehouses),
    path('api/warehouses/create/', views.addWarehouse),
    path('api/warehouses/read/<str:pk>/', views.getWarehouse),
    path('api/warehouses/update/<str:pk>/', views.updateWarehouse),
    path('api/warehouses/delete/<str:pk>/', views.deleteWarehouse),

    # # Template urls
    path('orders/search/', views.order_search, name='order_search'),
    path('orders/<str:pk>/', views.order_details, name='order_details'),
    path('create_order/', views.create_new_order, name='create_new_order'),
    path('order_success/', views.success_view, name='success'),  # Add a new URL for the success page

]

tracking/models.py
from django.db import models

# Create your models here

class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)

class Customer(models.Model):
    customer_name = models.CharField( null=False)
    customer_email = models.EmailField(null=False)
    customer_address = models.CharField(null=False)
    customer_phone = models.CharField(max_length=20, null=False)

    def serialize(self):
        return {
            'customer_id': self.id,
            'customer_name': self.customer_name,
            'customer_email': self.customer_email,
            'customer_address': self.customer_address,
            'customer_phone': self.customer_phone,
        }


class Order(models.Model):
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='orders', null=True, blank=True)
    
    sender_name = models.CharField(max_length=255)
    sender_address = models.CharField(max_length=255)
    sender_email = models.EmailField()
    sender_phone = models.CharField(max_length=20)
    sender_id = models.CharField(max_length=20, null = True)

    # Receiver Information
    receiver_id = models.CharField(max_length=20, null = True)
    receiver_name = models.CharField(max_length=255)
    receiver_address = models.CharField(max_length=255)
    receiver_phone = models.CharField(max_length=20)
    receiver_email =  models.EmailField()


    # Other Order Information
    origin_address = models.CharField(max_length=255, null=False)
    destination_address = models.CharField(max_length=255, null=False)
    order_status = models.CharField(max_length=50, null=True, default='pending' ) 
    order_date = models.DateTimeField(null=True)
    delivery_date = models.DateTimeField(null=True)
    estimated_delivery_date = models.DateTimeField(null=True)
    order_location = models.CharField(max_length=255, null=True)

    def serialize(self):
        return {
            'customer_id': self.customer_id if self.customer_id else None,
            
            'sender_name': self.sender_name,
            'receiver_name': self.receiver_name,
            'origin_address': self.origin_address,
            'destination_address': self.destination_address,
            'order_status': self.order_status,
            'order_date': self.order_date.isoformat(),
            'delivery_date': self.delivery_date.isoformat() if self.delivery_date else None,
            'estimated_delivery_date': self.estimated_delivery_date.isoformat() if self.estimated_delivery_date else None,
            'order_location': self.order_location,
            'customer_name' : self.customer_id__customer_name

        }


class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=255, null=False)
    quantity = models.IntegerField(null=False)
    weight = models.FloatField(null=False)

    def serialize(self):
        return {
            'item_id': self.id,
            'order_id': self.order.id,
            'item_name': self.item_name,
            'quantity': self.quantity,
            'weight': self.weight,
        }

from django.db import models

class Transaction(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=50, null=False)
    amount = models.FloatField(null=False)
    transaction_date = models.DateTimeField(null=False)
    payment_method = models.CharField(max_length=50, null=False)
    transaction_status = models.CharField(max_length=50, null=False)

    def serialize(self):
        return {
            'transaction_id': self.id,
            'order_id': self.order_id,
            'sender_id': self.sender_id,
            'receiver_id': self.receiver_id,
            'transaction_type': self.transaction_type,
            'amount': self.amount,
            'transaction_date': self.transaction_date.isoformat(),
            'payment_method': self.payment_method,
            'transaction_status': self.transaction_status,
        }

class Warehouse(models.Model):
    warehouse_name = models.CharField(max_length=255, null=False)
    warehouse_location = models.CharField(max_length=255, null=False)

    def serialize(self):
        return {
            'warehouse_id': self.id,
            'warehouse_name': self.warehouse_name,
            'warehouse_location': self.warehouse_location,
        }

tracking/forms.py
from django import forms
from . import models

class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = [
            'sender_name',
            'sender_address',
            'sender_email',
            'sender_phone',
            'receiver_name',
            'receiver_address',
            'receiver_email',
            'receiver_phone',
            'origin_address',
            'destination_address',
        ]

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        # Add widget attributes or any other customization as needed

tracking/views.py
# views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .models import User, Customer, Order, OrderItem, Transaction, Warehouse
from .serializers import UserSerializer, CustomerSerializer, OrderSerializer, OrderItemSerializer, TransactionSerializer, WarehouseSerializer
import requests
from django.http import HttpResponse  # Adjust the import based on your needs
from django.core.serializers import serialize
from rest_framework import status
from django.shortcuts import render, redirect
from . import forms

def my_view(request):
    # Your view logic here
    # ...

    # Redirect the user to a different URL
    return redirect('some_other_url_name')

# # # # # # # # # # # #    API views # # # # # # # # # # # # 
# User views
@api_view(['GET'])
def getUsers(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getUser(request, pk):
    user = User.objects.get(id=pk)
    serializer = UserSerializer(user, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def addUser(request):
    serializer = UserSerializer(data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)


@api_view(['PUT'])
def updateUser(request, pk):
    user = User.objects.get(id=pk)
    serializer = UserSerializer(instance=user, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)


@api_view(['DELETE'])
def deleteUser(request, pk):
    user = User.objects.get(id=pk)
    user.delete()
    
    return Response('User successfully deleted!')

# # # # # # # # # # # # # # # # # # # Customer views
@api_view(['GET'])
def getCustomers(request):
    customers = Customer.objects.all()
    serializer = CustomerSerializer(customers, many=True)
    return Response(serializer.data)

@api_view(['GET' ])
def getCustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    serializer = CustomerSerializer(customer, many=False)
    return Response(serializer.data)

@api_view(['POST'])
def addCustomer(request):
    serializer = CustomerSerializer(data=request.data)
    
    try:
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(['PUT'])
def updateCustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    serializer = CustomerSerializer(instance=customer, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteCustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    customer.delete()
    
    return Response('Customer successfully deleted!')



# # # # # # # # # # # # # # # # # # # # # # # # # Order views

@api_view(['GET' , 'POST'])
def getOrders(request):
    orders = Order.objects.all()
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

@api_view(['GET' , 'POST'])
def getOrder(request, pk):
    order = Order.objects.get(id=pk)
    serializer = OrderSerializer(order, many=False)
    return Response(serializer.data)

@api_view(['POST' , 'GET'])
def addOrder(request):
    serializer = OrderSerializer(data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['PUT'])
def updateOrder(request, pk):
    order = Order.objects.get(id=pk)
    serializer = OrderSerializer(instance=order, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteOrder(request, pk):
    order = Order.objects.get(id=pk)
    order.delete()
    
    return Response('Order successfully deleted!')


# # # # # # # # # # # # # # # # # # # # # # # # # # # # OrderItem views


@api_view(['GET' , 'POST'])
def getOrderItems(request):
    order_items = OrderItem.objects.all()
    serializer = OrderItemSerializer(order_items, many=True)
    return Response(serializer.data)

@api_view(['GET' , 'POST'])
def getOrderItem(request, pk):
    order_item = OrderItem.objects.get(id=pk)
    serializer = OrderItemSerializer(order_item, many=False)
    return Response(serializer.data)

@api_view(['POST' , 'GET'])
def addOrderItem(request):
    serializer = OrderItemSerializer(data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['PUT'])
def updateOrderItem(request, pk):
    order_item = OrderItem.objects.get(id=pk)
    serializer = OrderItemSerializer(instance=order_item, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteOrderItem(request, pk):
    order_item = OrderItem.objects.get(id=pk)
    order_item.delete()
    
    return Response('OrderItem successfully deleted!')




# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # Transaction views

@api_view(['GET' , 'POST'])
def getTransactions(request):
    transactions = Transaction.objects.all()
    serializer = TransactionSerializer(transactions, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getTransaction(request, pk):
    transaction = Transaction.objects.get(id=pk)
    serializer = TransactionSerializer(transaction, many=False)
    return Response(serializer.data)

@api_view(['POST'])
def addTransaction(request):
    serializer = TransactionSerializer(data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['PUT'])
def updateTransaction(request, pk):
    transaction = Transaction.objects.get(id=pk)
    serializer = TransactionSerializer(instance=transaction, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteTransaction(request, pk):
    transaction = Transaction.objects.get(id=pk)
    transaction.delete()
    
    return Response('Transaction successfully deleted!')



# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # Warehouse views

@api_view(['GET'])
def getWarehouses(request):
    warehouses = Warehouse.objects.all()
    serializer = WarehouseSerializer(warehouses, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getWarehouse(request, pk):
    warehouse = Warehouse.objects.get(id=pk)
    serializer = WarehouseSerializer(warehouse, many=False)
    return Response(serializer.data)

@api_view(['POST'])
def addWarehouse(request):
    serializer = WarehouseSerializer(data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['PUT'])
def updateWarehouse(request, pk):
    warehouse = Warehouse.objects.get(id=pk)
    serializer = WarehouseSerializer(instance=warehouse, data=request.data)
    
    if serializer.is_valid():
        serializer.save()
    
    return Response(serializer.data)

@api_view(['DELETE'])
def deleteWarehouse(request, pk):
    warehouse = Warehouse.objects.get(id=pk)
    warehouse.delete()
    
    return Response('Warehouse successfully deleted!')



# # # # #  template views # # # # # # # 


def order_search(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')

        try:
            # Fetch the order with the given ID
            order = Order.objects.get(id=order_id)

            # Serialize the order data
            serialized_order = OrderSerializer(order).data

            # Render the template with the order details
            return render(request, 'tracking_display.html', {'order': serialized_order})
        except Order.DoesNotExist:
            return HttpResponse("Order not found", status=404)

    return render(request, 'tracking_search.html')



from django.shortcuts import render, get_object_or_404

def order_details(request, pk):
    try:
        order = get_object_or_404(Order, id=pk)

        # Access the customer name through the related field
        customer_name = order.customer_id.customer_name

        # Add the customer name to the serialized order data
        serialized_order = OrderSerializer(order).data
        serialized_order['customer_name'] = customer_name

        # Render the template with the order details
        return render(request, 'tracking_display.html', {'order': serialized_order})
    except Order.DoesNotExist:
        return HttpResponse("Order not found", status=404)




def success_view(request):
    return render(request, 'success.html')




API_ENDPOINT = 'http://127.0.0.1:8000/api/orders/create/'  # Replace with your actual API endpoint

def create_new_order(request):
    if request.method == 'POST':
        form = forms.OrderForm(request.POST)
        if form.is_valid():
            # Save the form data to the database
            form.save()

            # Extract form data
            form_data = form.cleaned_data

            # Make a POST request to the API
            api_data = {
                'sender_name': form_data['sender_name'],
                'sender_address': form_data['sender_address'],
                'sender_email': form_data['sender_email'],
                'sender_phone': form_data['sender_phone'],
                'receiver_name': form_data['receiver_name'],
                'receiver_address': form_data['receiver_address'],
                'receiver_phone': form_data['receiver_phone'],
                'receiver_email': form_data['receiver_email'],
                'origin_address': form_data['origin_address'],

tracking/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="order.css" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    />
    <title>Shipment Information Form</title>
  </head>
  <body class="bg-light">
    <div class="container mt-5">
      <h2 class="mb-4">Shipment Information Form</h2>
      <form>
        <div class="row">
          <!-- Sender Part -->
          <div class="col-md-6">
            <h3>Sender Information</h3>
            <div class="form-group">
              <label for="inputSenderName">Name</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderName"
                placeholder="Enter sender's name"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderSurname">Surname</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderSurname"
                placeholder="Enter sender's surname"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderAddress">Sender Address</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderAddress"
                placeholder="Enter sender's address"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderEmail">Email</label>
              <input
                type="email"
                class="form-control"
                id="inputSenderEmail"
                placeholder="Enter sender's email"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderPhone">Phone</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderPhone"
                placeholder="Enter sender's phone number"
                required
              />
            </div>
          </div>

          <!-- Receiver Part -->
          <div class="col-md-6">
            <h3>Receiver Information</h3>
            <div class="form-group">
              <label for="inputReceiverName">Name</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverName"
                placeholder="Enter receiver's name"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputReceiverSurname">Surname</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverSurname"
                placeholder="Enter receiver's surname"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputReceiverAddress">Receiver Address</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverAddress"
                placeholder="Enter receiver's address"
                required
              />
            </div>
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="order.js"></script>
  </body>
</html>

tracking/templates/order.html
{% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <title>Shipment Information Form</title>
  </head>
  <body style="background-color: #f8f9fa;">
    <div class="container mt-5" style="background-color: #ffffff; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
      <br> <br>
      <form method="post" action="{% url 'tracking:create_new_order' %}">
        {% csrf_token %}
        <div class="row">
          <!-- Sender Part -->
          <div class="col-md-6">
            <h3 style="color: #007bff;">Sender Information</h3>
            <div class="form-group">
              <label for="inputSenderName" style="color: #495057;">Name</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderName"
                name="sender_name"
                placeholder="Enter sender's name"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderAddress" style="color: #495057;">Sender Address</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderAddress"
                name="sender_address"
                placeholder="Enter sender's address"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderEmail" style="color: #495057;">Email</label>
              <input
                type="email"
                class="form-control"
                id="inputSenderEmail"
                name="sender_email"
                placeholder="Enter sender's email"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputSenderPhone" style="color: #495057;">Phone</label>
              <input
                type="text"
                class="form-control"
                id="inputSenderPhone"
                name="sender_phone"
                placeholder="Enter sender's phone number"
                required
              />
            </div>
          </div>

          <!-- Receiver Part -->
          <div class="col-md-6">
            <h3 style="color: #007bff;">Receiver Information</h3>
            <div class="form-group">
              <label for="inputReceiverName" style="color: #495057;">Name</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverName"
                name="receiver_name"
                placeholder="Enter receiver's name"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputReceiverAddress" style="color: #495057;">Receiver Address</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverAddress"
                name="receiver_address"
                placeholder="Enter receiver's address"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputReceiverEmail" style="color: #495057;">Email</label>
              <input
                type="email"
                class="form-control"
                id="inputReceiverEmail"
                name="receiver_email"
                placeholder="Enter receiver's email"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputReceiverPhone" style="color: #495057;">Phone</label>
              <input
                type="text"
                class="form-control"
                id="inputReceiverPhone"
                name="receiver_phone"
                placeholder="Enter receiver's phone number"
                required
              />
            </div>
          </div>

          <!-- Additional Order Information -->
          <div class="col-md-6">
            <h3 style="color: #007bff;">Other Order Information</h3>
            <div class="form-group">
              <label for="inputOriginAddress" style="color: #495057;">Origin Address</label>
              <input
                type="text"
                class="form-control"
                id="inputOriginAddress"
                name="origin_address"
                placeholder="Enter origin address"
                required
              />
            </div>
            <div class="form-group">
              <label for="inputDestinationAddress" style="color: #495057;">Destination Address</label>
              <input
                type="text"
                class="form-control"
                id="inputDestinationAddress"
                name="destination_address"
                placeholder="Enter destination address"
                required
              />
            </div>
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

{% endblock %}

tracking/templates/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    />
    <title>Success</title>
  </head>
  <body>
    <div class="container mt-5 text-center">
      <h2 class="text-success">Shipment Details Sent Successfully!</h2>
      <p>Your shipment details have been successfully submitted. Thank you!</p>
    </div>
  </body>
</html>

tracking/templates/tracking_display.html
{% block content %}
    <style>
        .order-details {
            border: 1px solid #ccc;
            padding: 20px;
            margin: 20px;
            border-radius: 10px;
            /* background-color: #add8e6;  */
            color: black; /* Text color set to white */
        }

        .order-field {
            margin-bottom: 10px;
        }

        .field-label {
            font-weight: bold;
            margin-right: 10px;
        }

        .field-value {
            color: #333;
        }
    </style>

    <div class="order-details">
        <div class="order-field">
            <span class="field-label">Customer Name:</span>
            <span class="field-value">{{ order.customer_name }}</span>

        </div>

        <div class="order-field">
            <span class="field-label">Origin Address:</span>
            <span class="field-value">{{ order.origin_address }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Destination Address:</span>
            <span class="field-value">{{ order.destination_address }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Order Status:</span>
            <span class="field-value">{{ order.order_status }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Order Date:</span>
            <span class="field-value">{{ order.order_date }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Delivery Date:</span>
            <span class="field-value">{{ order.delivery_date }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Estimated Delivery Date:</span>
            <span class="field-value">{{ order.estimated_delivery_date }}</span>
        </div>

        <div class="order-field">
            <span class="field-label">Order Location:</span>
            <span class="field-value">{{ order.order_location }}</span>
        </div>
    </div>
{% endblock %}